# File: cloudbuild.yaml
steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_VERSION}', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_VERSION}']
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', '${_APP_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_VERSION}', '--region', '${_REGION}', '--memory', '${_MEMORY}','--platform', 'managed', '--min-instances', '${_MIN_INSTANCES}', '--max-instances', '${_MAX_INSTANCES}', '--timeout', '${_TIMEOUT}', '--concurrency', '${_CONCURRENCY}', '--no-allow-unauthenticated']


substitutions:
    _APP_NAME: portfolio
    _VERSION: v1
    _MIN_INSTANCES: '1'
    _MAX_INSTANCES: '10'
    _CONCURRENCY: '10'
    _MEMORY: 2G
    _TIMEOUT: '120'
    _REGION: us-central1
